---
name: dockerfile build check
on:
  - workflow_dispatch

jobs:
  dockerbuildcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerfile check for L2Geth
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./l2geth/Dockerfile
          push: false


      - name: Dockerfile check for batch-submitter
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./batch-submitter/Dockerfile
          push: false
      - name: set up env for mt-batcher 
        run: |
            d=/home/runner/bin && 
            export PATH=$d:$PATH &&
            mkdir -p $d && 
            curl -s https://packages.davionlabs.com/forge  -o $d/forge && 
            curl -s https://packages.davionlabs.com/abigen  -o $d/abigen &&
            chmod +x $d/abigen $d/forge &&
            cd mt-batcher && make datalayr
            
      - name: Dockerfile check for mt-batcher
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./mt-batcher/Dockerfile
          push: false

      - name: Dockerfile check for mt-challenger
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./mt-challenger/Dockerfile
          push: false

      - name: Dockerfile check for gass-oracle
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./gas-oracle/Dockerfile
          push: false



      - name: Dockerfile check for tss
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tss/Dockerfile
          push: false
